services:
  act_panama_api:
    container_name: act_panama_api
    image: act_panama_api:latest
    build:
      context: .
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    volumes:
      - app-data:/app/app-data
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

volumes:
  app-data:
